# Site settings
title: Stanford Tape and Scissors
email: stanfordtapeandscissors@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stanford Tape and Scissors is a subgroup of Stanford University's
  Solar and Wind Energy Project (SWEP). 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stanfordtapeandscissors.github.io" # the base hostname & protocol for your site
twitter_username: stanfordtapeandscissors
github_username:  stanfordtapeandscissors

# Contact form: comment the line below if you want to stick with the default PHP contact form
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 90CDEA #80B3FF
  secondary: 6077A0 #FD6E8A
  secondary-dark: 0B1646 #A2122F

# Footer settings
footer:
  location: Stanford, California
  credits: Stanford University Department of Civil and Environmental Engineering

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/stanfordtapeandscissors/stanfordtapeandscissors.github.io

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'This website is built off of a Bootstrap layout and hosted on GitHub Pages'

# Build settings
markdown: kramdown
permalink: pretty
